# Generated by Django 2.2.6 on 2019-11-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_title', models.TextField()),
                ('track_author', models.TextField(default='UNKNOWNAUTHOR')),
                ('track_album', models.TextField(default='UNKNOWNALBUM')),
            ],
            options={
                'verbose_name_plural': 'Tracks',
            },
        ),
    ]
