# Generated by Django 2.2.6 on 2019-11-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goosy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_album',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_author',
            field=models.TextField(),
        ),
    ]
